---
- name: Install Rundeck
  hosts: all
  become: yes
  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Rundeck APT repository
      apt_repository:
        repo: 'deb https://rundeck.bintray.com/rundeck-deb /'
        state: present

    - name: Add Rundeck APT key
      apt_key:
        url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Rundeck
      apt:
        name: rundeck
        state: present

    - name: Start Rundeck service
      service:
        name: rundeckd
        state: started
        enabled: yes
